# Библиотеки Numpy, и немного Pandas

In [1]:
import numpy as np
import pandas as pd
import copy

## Numpy: зачем нужна ты сама примерно знаешь
***Очень удобно, быстро и красиво работать с матрицами***

In [2]:
# Как создать массив?
x = [ 6, 7., 5, 8, 0, 1]
arr = np.array(x) 
arr

array([6., 7., 5., 8., 0., 1.])

In [7]:
# Можно так:
print( np.arange(5) )
print( np.zeros(5, dtype='complex') ) # dtype -> тип значений, которые хранит массив
print( np.linspace(0, 1, 6) ) # 6 значений в равномерно интервале [-2, 2]
print( np.logspace(0, 1, 6) ) # 6 значений в равномерно интервале [-2, 2]
print()
print( np.ones((2, 3)) ) # Обрати внимание на двойные скобки: многомерный массив создается из tuple
print()
print( np.eye(3) )

[0 1 2 3 4]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[0.  0.2 0.4 0.6 0.8 1. ]
[ 1.          1.58489319  2.51188643  3.98107171  6.30957344 10.        ]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Операции над массивами

In [13]:
arr1 = np.array([[1., 2., 3.], [2., 3., 4.]]) 
arr2 = np.array([[3., 4., 5.], [4., 5., 6.]])
arr1

array([[1., 2., 3.],
       [2., 3., 4.]])

In [9]:
arr1 + 10

array([[11., 12., 13.],
       [12., 13., 14.]])

In [118]:
arr1 + arr2

array([[ 4.,  6.,  8.],
       [ 6.,  8., 10.]])

In [10]:
arr1 * arr2 # Поэлементное умножение

array([[ 3.,  8., 15.],
       [ 8., 15., 24.]])

In [14]:
print(arr1.mean())
print(arr1.std())
print(arr1.max(axis=1)) # по какому измерению считать
print(arr1.argmax(axis=1)) # индекс, на котором достигается максимум
print(arr1.sum(axis=0))
print(arr1.cumsum())
print()


2.5
0.9574271077563381
[3. 4.]
[2 2]
[3. 5. 7.]
[ 1.  3.  6.  8. 11. 15.]



In [18]:
# array.T -> Транспонирование
np.matmul(arr1.T, arr2) # Матричное умножение
# np.dot(arr1[0], arr2[0]) # По факту то же самое, но по семантике -> скалярное произведение

array([[11., 14., 17.],
       [18., 23., 28.],
       [25., 32., 39.]])

In [47]:
arr1.reshape(1, 6)
# arr1.reshape(1, -1) # -1, если этот параметр должен быть подобран автоматически

array([[1., 2., 3., 2., 3., 4.]])

In [12]:
print(arr1.shape) # размер массива по измерениям
print(arr1.size) # Полный размер массива

(2, 3)
6


In [19]:
# Индексирование: 
# Мне кажется это и с обычными списками работает, когда научишься пользоваться - очень полезно
arr = np.arange(10)
print(arr)
indexes = [1, 5, 3, 1, 1, 1, 9, 6]
print(indexes)
print(arr[[0, 1]]) # Круто?
print(arr[indexes]) # Круто?

[0 1 2 3 4 5 6 7 8 9]
[1, 5, 3, 1, 1, 1, 9, 6]
[0 1]
[1 5 3 1 1 1 9 6]


# Задание 1
***Написать функцию для нахождения определитеня матрицы методом Гаусса***

In [87]:
# Не пользоваться np.linalg.det # Да, нелогично, я же тебя учу библиотеке, но начнем с малого
# Пользоваться операциями C массивами (строками)
def determinant(X_given):
    X = copy.deepcopy(X_given) # мы же не хотим испортить ту матрицу
    det = 1
    m = X.shape[0]
    n = X.shape[1]
    # Your code here
    # ...
    if m != n:
        raise RuntimeError()
        
    for i in range(n - 1):
        if X[i][i] == 0:
            tmp = False
            for k in range(i + 1, n):
                if X[k][i] != 0:
                    t = np.copy(X[i])
                    X[i] = X[k]
                    X[k] = np.copy(t)
                    det *= -1
                    tmp = True
                    break
            if not tmp:
                return 0
        print(X)
        for j in range(i + 1, n):
            X[j] -= X[i] * X[j][i] / X[i][i]
    
    for i in range(n):
        det *= X[i][i]
    
    print(X)
    return det

In [88]:
a = np.arange(4).reshape(2, 2).astype(float)
a

array([[0., 1.],
       [2., 3.]])

In [89]:
determinant(a)

[[2. 3.]
 [0. 1.]]
[[2. 3.]
 [0. 1.]]


-2.0

***Написать функцию для нахождения решения системы уравнений используя матричные операции***

In [46]:
def eq_system_solution(a, b):
    # Так можно писать документацию к функции
    """
    Нахидт решение системы линейных уравнений Ax = b c невырожденной матрицей A
    Результат: вектор x -> решение системы
    """
    # Может ли тебе пригодиться предыдущая функция?
    # Не забывай работать с матрицами, можно использовать всё
    
    # Your code here
    # ...
    
    return 0

In [43]:
# np.linalg - это отдельный модуль, в котором есть работа с матрицами и многое из линейное алгебры
# Часто может пригодиться

# Библиотека Pandas
## Pandas.Series

In [56]:
s1 = pd.Series([5, 6, 7, 8, 9])
print(s1)

s1.values # перевод в np.array

0    5
1    6
2    7
3    8
4    9
dtype: int64


array([5, 6, 7, 8, 9])

***Первый столбец: индексы, второй: значения***  
То есть чем-то похоже на упорядоченный словарь

In [57]:
s2 = pd.Series([5, 6, 7, 8, 9, 10], index=['a', 'b', 'c', 'd', 'e', 'f'])
s2
# можно явно задавать индексы

a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64

## Pandas.Dataframe
***Таблица, состаящая из различных пар: Название столбца, pd.Series***

In [58]:
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [60]:
# обращение:
print(df.country)
# или так
print(df['country'])

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object
0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object


In [65]:
df.iloc[0:2, 1:3] # Возвращает "суб-таблицу" из данних строк, столбцов

population    square
0       17.04   2724902
1      143.50  17125191

In [73]:
df.iloc[[1, 3], [0, 1, 2]] # или так

country  population    square
1   Russia       143.5  17125191
3  Ukraine        45.5    603628

In [75]:
# чтение файлов
# df = pd.read_csv('file/path')
# df = pd.read_excel('file/path')

In [77]:
# Куча разных функций, лучше выучить по мере необходимости, можно посмотреть в лекции из техносферы
# Вообще сложно выучить эту библиотеку так сразу, лучше на опыте научиться